version: '3.7'

services:
  hotelbe:
    container_name: hotelbe
    # restart: always
    build:
      context: .
      #   target: development
    env_file:
      - .env
    environment:
      - TZ=${TIMEZONE_ENV}
    volumes:
      - .:/usr/src/hotelbe
      - /usr/src/hotelbe/node_modules
    ports:
      - ${PORT}:${PORT}
      - 1978:1978
    command: npm run start:dev
    #  command: npm run start
    depends_on:
      - db
      - hotelRedis
    networks:
      - webnet

  #  mysqldb:
  #    container_name: mysqldb
  #    restart: always
  #    image: mysql:5.7
       # image: mariadb:10.4
  #    environment:
  #      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
  #      MYSQL_USER: ${DB_USER}
  #      MYSQL_PASSWORD: ${DB_PASS}
  #      MYSQL_DATABASE: ${DB_NAME}
  #    ports:
  #      - '3306:3306'
  #    networks:
  #      - webnet
  #    volumes: 
  #      - db-data:/var/lib/mysql

  hotelRedis:
    container_name: hotelRedis
    image: redis:5
    ports:
      - '6380:6379'
    expose:
      - 6380
    networks:
      - webnet

  # mongodb:
  #   container_name: mongodb
  #   image: mongo:latest
  #   environment:
  #     - MONGODB_DATABASE: ${MONGODB_DATABASE}
  #   ports:
  #     - 27017:27017
  #   networks:
  #     - webnet

  db:
    container_name: db
    image: postgres
    # restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    networks:
      - webnet
    volumes:
      - db-data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 5454:5454/tcp
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    networks:
      - webnet

networks:
  webnet:

volumes: 
  db-data: